import { VerifyResponse } from "./types";

/** Mock response for development without backend. */
export const MOCK_RESPONSE: VerifyResponse = {
  input_type: "text",
  mode: "live",
  claims: [
    {
      id: "c1",
      claim: "The inflation rate in Italy is 2%.",
      type: "statistical",
      partial_verdict: "verified",
      partial_score: 87,
      checkability_score: 0.95,
    },
    {
      id: "c2",
      claim: "The European Central Bank raised interest rates.",
      type: "institutional",
      partial_verdict: "mostly_verified",
      partial_score: 72,
      checkability_score: 0.85,
    },
    {
      id: "c3",
      claim: "This caused a decline in consumer spending.",
      type: "causal",
      partial_verdict: "mixed",
      partial_score: 55,
      checkability_score: 0.4,
    },
  ],
  sources_used: [
    {
      source_id: "src_001",
      source_name: "ISTAT Official Statistics",
      source_type: "official",
      url: "https://www.istat.it",
      tier: "A",
      source_reliability_score: 0.93,
      dimensions: {
        authority: 1.0,
        expertise: 0.95,
        transparency: 0.9,
        independence: 0.85,
        recency: 0.95,
      },
    },
    {
      source_id: "src_002",
      source_name: "Reuters News",
      source_type: "news",
      url: "https://reuters.com",
      tier: "B",
      source_reliability_score: 0.78,
      dimensions: {
        authority: 0.7,
        expertise: 0.8,
        transparency: 0.75,
        independence: 0.85,
        recency: 0.9,
      },
    },
  ],
  all_sources_found: [
    {
      source_id: "src_001",
      source_name: "ISTAT Official Statistics",
      url: "https://www.istat.it/economia/inflazione",
      domain: "istat.it",
      score: 0.93,
      claim_ids: ["c1"],
      selection_reason: "high_recall_rank",
      forensic_score: 0.91,
      dimensions: {
        https: 1,
        author: 1,
        citation_density: 0.8,
        transparency: 0.9,
      },
    },
    {
      source_id: "src_002",
      source_name: "Reuters News",
      url: "https://www.reuters.com/world/europe/ecb-rates",
      domain: "reuters.com",
      score: 0.88,
      claim_ids: ["c2"],
      selection_reason: "high_recall_rank",
      forensic_score: 0.79,
      dimensions: {
        https: 1,
        author: 0.9,
        citation_density: 0.72,
        transparency: 0.76,
      },
    },
    {
      source_id: "src_003",
      source_name: "Finance Blog Mirror",
      url: "https://finance-blog.example/rates",
      domain: "finance-blog.example",
      score: 0.51,
      claim_ids: ["c2", "c3"],
      forensic_score: 0.34,
      forensic_flags: ["brand_mimicry_risk", "low_transparency"],
    },
  ],
  selected_sources: [
    {
      source_id: "src_001",
      source_name: "ISTAT Official Statistics",
      url: "https://www.istat.it/economia/inflazione",
      domain: "istat.it",
      score: 0.93,
      claim_ids: ["c1"],
      selection_reason: "high_recall_rank",
      forensic_score: 0.91,
      dimensions: {
        https: 1,
        author: 1,
        citation_density: 0.8,
        transparency: 0.9,
      },
    },
    {
      source_id: "src_002",
      source_name: "Reuters News",
      url: "https://www.reuters.com/world/europe/ecb-rates",
      domain: "reuters.com",
      score: 0.88,
      claim_ids: ["c2"],
      selection_reason: "high_recall_rank",
      forensic_score: 0.79,
      dimensions: {
        https: 1,
        author: 0.9,
        citation_density: 0.72,
        transparency: 0.76,
      },
    },
  ],
  rejected_sources: [
    {
      source_id: "src_003",
      url: "https://finance-blog.example/rates",
      reason: "domain_overrepresented",
      claim_id: "c2",
    },
  ],
  source_forensics: [
    {
      source_id: "src_001",
      url: "https://www.istat.it/economia/inflazione",
      domain: "istat.it",
      tld: "it",
      https: true,
      canonical_origin: "https://www.istat.it/economia/inflazione",
      brand_mimicry_risk: 0.05,
      low_quality_risk: 0.12,
      author_present: true,
      author_name: "ISTAT editorial team",
      citation_count: 8,
      citation_density: 0.8,
      about_links: 1,
      contact_links: 1,
      editorial_links: 1,
      published_at: "2026-03-02T08:00:00Z",
      forensic_score: 0.91,
      dimensions: {
        https: 1,
        author: 1,
        citation_density: 0.8,
        transparency: 0.9,
        brand_safety: 0.95,
        quality: 0.88,
      },
      flags: [],
    },
    {
      source_id: "src_002",
      url: "https://www.reuters.com/world/europe/ecb-rates",
      domain: "reuters.com",
      tld: "com",
      https: true,
      canonical_origin: "https://www.reuters.com/world/europe/ecb-rates",
      brand_mimicry_risk: 0.02,
      low_quality_risk: 0.18,
      author_present: true,
      author_name: "Reuters Staff",
      citation_count: 5,
      citation_density: 0.72,
      about_links: 1,
      contact_links: 1,
      editorial_links: 1,
      published_at: "2026-03-15T09:00:00Z",
      forensic_score: 0.79,
      dimensions: {
        https: 1,
        author: 0.9,
        citation_density: 0.72,
        transparency: 0.76,
        brand_safety: 0.98,
        quality: 0.82,
      },
      flags: [],
    },
  ],
  claim_scores: [
    {
      claim_id: "c1",
      claim: "The inflation rate in Italy is 2%.",
      support_score: 0.84,
      contradiction_score: 0,
      claim_coverage: 0.81,
      source_diversity: 0.67,
      temporal_alignment: 0.9,
      forensic_support: 0.91,
      confidence_score: 0.82,
      partial_score: 87,
      partial_verdict: "verified",
      direct_supporting_evidence: 1,
      direct_contradicting_evidence: 0,
      direct_evidence_count: 1,
    },
    {
      claim_id: "c2",
      claim: "The European Central Bank raised interest rates.",
      support_score: 0.68,
      contradiction_score: 0.05,
      claim_coverage: 0.7,
      source_diversity: 0.6,
      temporal_alignment: 0.88,
      forensic_support: 0.79,
      confidence_score: 0.73,
      partial_score: 72,
      partial_verdict: "mostly_verified",
      direct_supporting_evidence: 1,
      direct_contradicting_evidence: 0,
      direct_evidence_count: 1,
    },
    {
      claim_id: "c3",
      claim: "This caused a decline in consumer spending.",
      support_score: 0.28,
      contradiction_score: 0.12,
      claim_coverage: 0.35,
      source_diversity: 0.33,
      temporal_alignment: 0.72,
      forensic_support: 0.54,
      confidence_score: 0.39,
      partial_score: 55,
      partial_verdict: "mixed",
      direct_supporting_evidence: 0,
      direct_contradicting_evidence: 0,
      direct_evidence_count: 0,
    },
  ],
  evidence: [
    {
      source_id: "src_001",
      stance: "supporting",
      evidence_score: 0.91,
      excerpt:
        "Annual consumer price inflation was 2.0% in February 2026, according to ISTAT preliminary estimates.",
    },
    {
      source_id: "src_002",
      stance: "supporting",
      evidence_score: 0.74,
      excerpt:
        "The ECB confirmed a rate hike at its March meeting, raising the main refinancing rate by 25 basis points.",
    },
  ],
  contradictions: [],
  linguistic_risk: {
    sensationalism_score: 0.1,
    emotional_tone_score: 0.08,
    attribution_risk: 0.05,
    uncertainty_score: 0.15,
    manipulation_markers: [],
  },
  site_forensics: null,
  truth_score: 78,
  confidence_score: 0.76,
  verdict: "mostly_verified",
  explanation: {
    summary:
      "The content is largely supported, with minor caveats. (Truth score: 78/100, 3 claims analyzed, 2 evidence items)",
    why: "2 supporting evidence item(s) found (avg score: 0.83). The causal claim has limited direct evidence.",
    supporting_evidence: [
      "Annual consumer price inflation was 2.0% in February 2026, according to ISTAT preliminary estimates.",
      "The ECB confirmed a rate hike at its March meeting.",
    ],
    contradicting_evidence: [],
    source_analysis: [
      "ISTAT Official Statistics (official, tier A): reliability 0.93 (high reliability)",
      "Reuters News (news, tier B): reliability 0.78 (high reliability)",
    ],
    temporal_context: "1 claim(s) are time-sensitive. 2 evidence item(s) have publication dates.",
    caveats: [
      "The causal link between rate hikes and consumer spending decline requires more evidence.",
    ],
  },
  layer_outputs: {
    claim_decomposition: {
      claim_count: 3,
      claims: [
        { id: "c1", claim: "The inflation rate in Italy is 2%." },
        { id: "c2", claim: "The European Central Bank raised interest rates." },
        { id: "c3", claim: "This caused a decline in consumer spending." },
      ],
    },
    query_planning: {
      plans: [
        {
          claim_id: "c1",
          claim: "The inflation rate in Italy is 2%.",
          queries: ["Italy inflation rate 2 percent", "\"The inflation rate in Italy is 2%.\""],
        },
        {
          claim_id: "c2",
          claim: "The European Central Bank raised interest rates.",
          queries: ["ECB raised interest rates March 2026", "European Central Bank rates"],
        },
      ],
    },
    discovery: {
      all_sources_found_count: 3,
      selected_sources_count: 2,
      rejected_sources_count: 1,
    },
    verdict_consistency: {
      support: 0.6,
      contradiction: 0.06,
      coverage: 0.62,
      applied_rules: ["blocked_high_verdict_without_direct_support_for_c3"],
      verdict: "mostly_verified",
      truth_score: 78,
      confidence_score: 0.76,
    },
  },
  errors: [],
  timings: {
    input_normalizer: 0.01,
    claim_decomposition: 0.15,
    source_discovery: 1.2,
    evidence_analysis: 0.8,
    judge: 0.05,
  },
};
